from flask import jsonify, render_template, request
from . import main

@main.app_errorhandler(404)
def page_not_found(error):
    '''
    Return a 404 error
    This error is generated by Flask automatically so I need to check to see if the request
    accepts JSON but not HTML.
    '''
    if request.accept_mimetypes.accept_json and not request.accept_mimetypes.accept_html:
        response = jsonify({'error': 'not found'})
        response.status_code = 404
        return response
    return render_template('404.html'), 404

@main.app_errorhandler(500)
def internal_server_error(error):
    '''
    Return a 500 error
    This error is generated by Flask automatically so I need to check to see if the request
    accepts JSON but not HTML.
    '''
    if request.accept_mimetypes.accept_json and not request.accept_mimetypes.accept_html:
        response = jsonify({'error': 'internal server error'})
        response.status_code = 500
        return response
    return render_template('500.html'), 500